### ISSUE TITLE
The data file test.jsonl your provided may be incomplete.

### ISSUE THREAD

**Issue by afterQingming** [DecstionBack/AAAI_2020_CommonsenseQA#1]
The last line of this file is not in a complete json format. It seems something were dropped by mistake.

**Comment by DecstionBack** [comment]
Thanks for your reminder. I have updated the file and you can also download the file from the official leaderboard. In our experiments, we use *.concept, *._NL, *.wikigraphnew. The original file downloaded from the leaderboard is not used and we just put it in the data folder. Thanks again.
