### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by JackWhite-rwx** [DecstionBack/AAAI_2020_CommonsenseQA#3]
excuse me!when I run code,it have a error:

File "./AAAI_2020_CommonsenseQA/pytorch_transformers/tokenization_xlnet.py", line 85, in __init__
    self.sp_model = spm.SentencePieceProcessor()
UnboundLocalError: local variable 'spm' referenced before assignment

Could you help me?Thank you very much!

**Comment by DecstionBack** [comment]
This may be due to the environmental problem. You could try to install the missing packages by "pip install sentencepiece". If there are any problems, you can also refer to "https://github.com/google/sentencepiece".

**Comment by JackWhite-rwx** [comment]
> This may be due to the environmental problem. You could try to install the missing packages by "pip install sentencepiece". If there are any problems, you can also refer to "https://github.com/google/sentencepiece".

Thank you again,I successfully solved the error according to your method.
